#!/bin/bash
IMAGE="rstms/devbox:${DEV_VERSION:-latest}"
DEV_USER="${DEV_USER:-$(id -un)}"
DEV_SRC="${DEV_SRC:-$(pwd)/src}"
DEV_SSH_DIR="${DEV_SSH_DIR:-${HOME}/.ssh}"
docker run -it --rm \
  -h "${DEV_HOSTNAME:-devbox}" \
  -v "${DEV_SSH_DIR}:/home/${DEV_USER}/.ssh" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  -v "${DEV_SRC}:/home/${DEV_USER}/src" \
  ${IMAGE}
